[package]
name = "goblin-pyo3"
version = "0.1.0"
edition = "2021"

[lib]
name = "goblin"
crate-type = ["cdylib"]

[dependencies]
goblin = "0.7.1"
pyo3 = { version = "0.20.0", features = ["extension-module"] }
